apiVersion: batch/v1
kind: Job
metadata:
  name: cert-checker
spec:
  template:
    spec:
      containers:
      - name: cert-checker
        image: cert-checker:latest
        imagePullPolicy: Never
        args: ["50"]
      restartPolicy: Never
  backoffLimit: 1
